apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: talk
servers: 1
agents: 2
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 9000:9000
    nodeFilters:
      - loadbalancer
  - port: 32100:32100
    nodeFilters:
      - loadbalancer
  - port: 32200:32200
    nodeFilters:
      - loadbalancer
#registries:
#  create:
#    name: registry.localhost
#    host: "0.0.0.0"
#    hostPort: "5001"
hostAliases:
  - ip: 172.17.0.2
    hostnames:
      - argo.k8s.edu.local
      - argocd.k8s.edu.local
      - phpldapadmin.k8s.edu.local
      - ltb.k8s.edu.local
      - ldap.k8s.edu.local
      - keycloak.k8s.edu.local
      - gitea.git.k8s.edu.local
      - git.k8s.edu.local
      - gitea.k8s.edu.local
      - rancher.k8s.edu.local
      - k8s.edu.local
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*